### ISSUE TITLE
Finisher fails if default list is empty

### ISSUE THREAD

**Issue by andre-spindler** [studiomitte/brevo#2]
Environment:
TYPO3 10.4.21
PHP 7.4.25
EXT:sendinblue dev-master #9c84efa

When the default list ist empty (no entry defined in the global extension settings), the compiled array is not accepted by sendmail.

Details, the error occurs in \StudioMitte\Sendinblue\Finishers\SendinblueFinisher::getEnrichedListIds():
If no default list is defined, the getter returns an empty array. That's correct so far.
But important, the internal array pointer is set to "1", not "0".
So when running through the custom list of the current finisher, the first new list is defined with array pointer "1".
As the senmail API requires array pointer "0" to be set, this fails.

I have a screenshot here, first debug output shows $lists right after fetching it with "$lists = $this->extensionConfiguration->getDefaultListIds();".
The second one shows $lists just befor returning it as the result.
Default list is empty, cutoms list id defined within the finisher configuration is id=5:
![grafik](https://user-images.githubusercontent.com/5618751/143325533-997949c0-4727-4c44-ae82-c420e8cf46c3.png)

Solution/fix:
Just call "array_values()" for $lists after getting the default lists:
![grafik](https://user-images.githubusercontent.com/5618751/143325750-f5062154-04c2-46b3-af14-5d1431e8fb3d.png)
New debug output:
![grafik](https://user-images.githubusercontent.com/5618751/143325798-0369a394-5ac7-4277-8eeb-3ba2c9af2e5b.png)

The fix will solve the issue, but this seems to be more an core issue, if I would expect an empty array as return value also starts with pointer at "0".

**Comment by andre-spindler** [comment]
Patch file

**Comment by h3nn3s** [comment]
I think, this is not valid anymore since Georg reworked the corresponding parts after this issue was created.
