### ISSUE TITLE
Error 503 with TYPO3 11.5

### ISSUE THREAD

**Issue by LinkPool2** [studiomitte/brevo#4]
After upgrading to TYPO3 11.5:

503Oops, an error occurred!
The finisher preset identified by "Sendinblue" could not be found, or the implementationClassName was not specified.
More information regarding this error might be available [online](https://typo3.org/go/exception/CMS/1328709784).

**Comment by LinkPool2** [comment]
ore: Exception handler (WEB): Uncaught TYPO3 Exception: #1328709784: The finisher preset identified by "Sendinblue" could not be found, or the implementationClassName was not specified. | 

TYPO3\CMS\Form\Domain\Model\Exception\FinisherPresetNotFoundException thrown in file /var/www/typo_src/typo3_src-11.5.21/typo3/sysext/form/Classes/Domain/Model/FormDefinition.php in line 553.

**Comment by Hogego** [comment]
seems that the extensions only works with TYPO3 10.x
Is there a way to integrate sendinblue into TYPO3 11.x ?

**Comment by h3nn3s** [comment]
There is a fork for v11 pending: https://github.com/studiomitte/sendinblue/pull/5
Did you test this one?

**Comment by georgringer** [comment]
fork is merged, all fine
