### ISSUE TITLE
Opt-In checkbox not working

### ISSUE THREAD

**Issue by Aero91** [studiomitte/brevo#8]
Hi,
E-Mail for DOI is sent, even if the checkbox is not active.

TYPO3 11.5.32
Extension 2.0.0

**Comment by 80Quattro** [comment]
Seems like AbstractFinisher->isEnabled() method ([BrevoFinisher line 109](https://github.com/studiomitte/brevo/blob/d4c7b7292074ef18ce3e28a454e19f596dacfb6d/Classes/Finishers/BrevoFinisher.php#L109C3-L109C3)) doesn't work as expected. I've made a PR.

**Comment by h3nn3s** [comment]
Hi,

I think this change is not working as expected.

"this->isEnabled()" checks renderingOptions.enabled = true which is the core was to enable or disable finishers
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.4/Feature-85080-AddPropertyDisableFormElementsAndFinishers.html

Your solutions requires me to set options.enabled = true

@georgringer I am wrong on this issue or can this change reverted and a new version released?
This breaks old behavior.

BR Henrik

**Comment by Aero91** [comment]
Unfortunately, I am still experiencing the issue. Even though the user does not check the checkbox, an email is still being sent by Brevo. Do I need to manually adjust something in the form configuration, or should the configuration in the form GUI be sufficient? My current configuration looks like this:

options:
  enabled: '{nl-checkbox}'
  firstName: '{name}'
  lastName: '{lastname}'
  email: '{email}'
  additionalListIds: ''
  tracking: contact-form
identifier: Brevo

**Comment by h3nn3s** [comment]
@Aero91 
I think the code is working correctly - but your config (and the one from the example form of this extension) is not correct.
The enable-flag must be nested under options.renderingOptions.enabled = '{nl-checkbox}'

I investigated on this, because we had a similar issue...

HTH Henrik

**Comment by h3nn3s** [comment]
see PR https://github.com/studiomitte/brevo/pull/15
